In [4]:
import pandas as pd
import numpy as np

In [6]:
from google.colab import files

uploaded = files.upload()

Saving students_raw.csv to students_raw.csv

In [8]:
df = pd.read_csv("students_raw.csv")

print("Loaded successfully!")

Loaded successfully!

In [9]:
df.head()

    Name  Math  Science  English  Attendance
0   Aman  86.0     87.0     69.0        65.0
1   Riya  49.0     36.0     69.0         NaN
2  Karan  95.0     94.0     67.0        87.0
3  Divya  55.0     78.0     39.0        79.0
4  Sahil  58.0     42.0     75.0        89.0

In [10]:
df.tail()

      Name  Math  Science  English  Attendance
38  Rakesh  48.0     45.0      NaN        92.0
39  Bhavna   NaN      NaN     76.0        60.0
40   Karan  95.0     94.0     67.0        87.0
41  Preeti  85.0     49.0     49.0        76.0
42   Divya  55.0     78.0     39.0        79.0

In [11]:
df.shape

(43, 5)

In [12]:
df.columns

Index(['Name', 'Math', 'Science', 'English', 'Attendance'], dtype='object')

In [13]:
df[["Name", "Math"]]

      Name  Math
0     Aman  86.0
1     Riya  49.0
2    Karan  95.0
3    Divya  55.0
4    Sahil  58.0
5     Neha  37.0
6    Rohan  56.0
7    Pooja   NaN
8   Aditya  36.0
9   Simran  64.0
10  Vikram  72.0
11  Anjali  36.0
12   Rahul  98.0
13   Kavya  94.0
14   Arjun  55.0
15   Meera  67.0
16  Suresh  92.0
17   Priya  56.0
18  Manish  83.0
19    Isha  93.0
20  Rajesh  76.0
21   Sneha  94.0
22   Vivek  49.0
23   Tanvi  96.0
24    Amit  96.0
25   Nisha  81.0
26  Deepak  96.0
27  Ritika  85.0
28  Gaurav  89.0
29   Swati   NaN
30   Harsh  37.0
31  Preeti  85.0
32  Sanjay  41.0
33   Komal  55.0
34    Yash  73.0
35  Shreya  52.0
36  Naveen  38.0
37   Anita  94.0
38  Rakesh  48.0
39  Bhavna   NaN
40   Karan  95.0
41  Preeti  85.0
42   Divya  55.0

In [14]:
df.loc[0:5]

    Name  Math  Science  English  Attendance
0   Aman  86.0     87.0     69.0        65.0
1   Riya  49.0     36.0     69.0         NaN
2  Karan  95.0     94.0     67.0        87.0
3  Divya  55.0     78.0     39.0        79.0
4  Sahil  58.0     42.0     75.0        89.0
5   Neha  37.0     81.0     62.0        70.0

In [15]:
df.iloc[0:5]

    Name  Math  Science  English  Attendance
0   Aman  86.0     87.0     69.0        65.0
1   Riya  49.0     36.0     69.0         NaN
2  Karan  95.0     94.0     67.0        87.0
3  Divya  55.0     78.0     39.0        79.0
4  Sahil  58.0     42.0     75.0        89.0

### loc vs iloc

loc  → works with index labels
       0:5 includes 0, 1, 2, 3, 4, 5

iloc → works with integer positions
       0:5 includes 0, 1, 2, 3, 4

In [16]:
# Select students who scored more than 80 in Math
df[df["Math"] > 80]

      Name  Math  Science  English  Attendance
0     Aman  86.0     87.0     69.0        65.0
2    Karan  95.0     94.0     67.0        87.0
12   Rahul  98.0     88.0     96.0        72.0
13   Kavya  94.0      NaN     71.0        62.0
16  Suresh  92.0     52.0     99.0        67.0
18  Manish  83.0     68.0     37.0        68.0
19    Isha  93.0     96.0     35.0         NaN
21   Sneha  94.0      NaN     48.0        83.0
23   Tanvi  96.0     96.0     43.0        91.0
24    Amit  96.0     74.0     49.0        91.0
25   Nisha  81.0     87.0     76.0        83.0
26  Deepak  96.0     58.0     85.0        71.0
27  Ritika  85.0     60.0      NaN        98.0
28  Gaurav  89.0     94.0     86.0        61.0
31  Preeti  85.0     49.0     49.0        76.0
37   Anita  94.0     97.0     93.0        91.0
40   Karan  95.0     94.0     67.0        87.0
41  Preeti  85.0     49.0     49.0        76.0

df["Math"] > 80
→ checks which students have Math marks greater than 80

In [17]:
# Sort students by Math marks from highest to lowest
df.sort_values("Math", ascending=False)

      Name  Math  Science  English  Attendance
12   Rahul  98.0     88.0     96.0        72.0
26  Deepak  96.0     58.0     85.0        71.0
23   Tanvi  96.0     96.0     43.0        91.0
24    Amit  96.0     74.0     49.0        91.0
2    Karan  95.0     94.0     67.0        87.0
40   Karan  95.0     94.0     67.0        87.0
37   Anita  94.0     97.0     93.0        91.0
21   Sneha  94.0      NaN     48.0        83.0
13   Kavya  94.0      NaN     71.0        62.0
19    Isha  93.0     96.0     35.0         NaN
16  Suresh  92.0     52.0     99.0        67.0
28  Gaurav  89.0     94.0     86.0        61.0
0     Aman  86.0     87.0     69.0        65.0
31  Preeti  85.0     49.0     49.0        76.0
41  Preeti  85.0     49.0     49.0        76.0
27  Ritika  85.0     60.0      NaN        98.0
18  Manish  83.0     68.0     37.0        68.0
25   Nisha  81.0     87.0     76.0        83.0
20  Rajesh  76.0     48.0     39.0        92.0
34    Yash  73.0     43.0     70.0        87.0
10  Vikram  72.0     36.0     82.0        60.0
15   Meera  67.0     97.0     69.0        65.0
9   Simran  64.0     38.0     67.0        92.0
4    Sahil  58.0     42.0     75.0        89.0
6    Rohan  56.0     69.0     41.0        87.0
17   Priya  56.0     78.0     81.0         NaN
14   Arjun  55.0     88.0     78.0        98.0
3    Divya  55.0     78.0     39.0        79.0
33   Komal  55.0     99.0     63.0        61.0
42   Divya  55.0     78.0     39.0        79.0
35  Shreya  52.0     35.0     47.0        82.0
1     Riya  49.0     36.0     69.0         NaN
22   Vivek  49.0     49.0     61.0        74.0
38  Rakesh  48.0     45.0      NaN        92.0
32  Sanjay  41.0     79.0      NaN        61.0
36  Naveen  38.0     42.0     66.0        96.0
30   Harsh  37.0     63.0     57.0        96.0
5     Neha  37.0     81.0     62.0        70.0
8   Aditya  36.0     84.0     68.0        98.0
11  Anjali  36.0     40.0     57.0        86.0
7    Pooja   NaN     70.0     46.0        84.0
29   Swati   NaN     75.0     38.0        62.0
39  Bhavna   NaN      NaN     76.0        60.0

In [18]:
# Display only the top scorer in Math
df.sort_values("Math", ascending=False).head(1)

     Name  Math  Science  English  Attendance
12  Rahul  98.0     88.0     96.0        72.0

## Session 1: Pandas Basics

In this session, I practiced:
- Loading a CSV dataset using Pandas
- Viewing the first and last rows using `head()` and `tail()`
- Checking dataset shape and column names
- Selecting specific columns
- Using `loc` and `iloc`
- Filtering students based on Math marks
- Sorting the dataset to find the top Math scorer